run:
  deadline: 5m
  tests: false
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - scopelint # deprecated
    - golint # deprecated
    - maligned # deprecated
    - interfacer # deprecated
    - varnamelen
    - tagliatelle
    - ireturn
    - funlen
    - godot
    - godox
    - lll
    - cyclop
