run:
  deadline: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - scopelint # deprecated
    - golint # deprecated
    - maligned # deprecated
    - interfacer # deprecated
    - varnamelen
    - ireturn
    - funlen
    - godox
    - lll
    - cyclop

linters-settings:
  tagliatelle:
    case:
      rules:
        json: snake